### ISSUE TITLE
drplot harvester cannot join farmer

### ISSUE THREAD

**Issue by griddis** [Chia-Network/drplotter#65]
Hello, 
everything worked until today, and this morning messages like these started appearing, while it seems like farming continues, but nothing is displayed in the interface
version 2.3.1
drplot 1.0.3

2024-06-07T05:43:56.338 harvester harvester_server        : ERROR    Exception: 'PlotManager' object has no attribute 'drplots' <class 'AttributeError'>, closing connection PeerInfo(_ip=IPv4Address('10.32.232.3'), _port=8447). Traceback (most recent call last):
  File "/app/chia/server/ws_connection.py", line 425, in _api_call
  File "/app/asyncio/tasks.py", line 445, in wait_for
  File "/app/chia/server/ws_connection.py", line 404, in wrapped_coroutine
  File "/app/chia/harvester/harvester_api.py", line 65, in harvester_handshake
  File "/app/chia/plot_sync/sender.py", line 180, in start
  File "/app/chia/plot_sync/sender.py", line 219, in _reset
AttributeError: 'PlotManager' object has no attribute 'drplots'

**Comment by griddis** [comment]
A complete restart of drchia helped.
